#pragma once

#include "CpuOpcode.h"
#include <ostream>

//----------------------------------------------------------------------------------------------------------------------
// Module that prints 'C++' code for a module.
//
// Basically produces a series of functions and statements which mimic the functionality of the original machine code.
// The statements generated use macros representing each CPU operation, register etc. and map pretty directly to similar
// output generated by the disassembler. These macros are to be defined by the host C++ program to perform the equivalent
// operations natively in the host environment.
//----------------------------------------------------------------------------------------------------------------------
struct ExeFile;

namespace PseudoCppPrinter {
    void printCpp(const ExeFile& exe, std::ostream& out);
}
