#pragma once

struct mobj_t;

bool P_CheckMeleeRange(mobj_t& attacker) noexcept;
bool P_CheckMissileRange(mobj_t& attacker) noexcept;
bool P_Move(mobj_t& actor) noexcept;
bool P_TryWalk(mobj_t& actor) noexcept;
void P_NewChaseDir(mobj_t& actor) noexcept;
bool P_LookForPlayers(mobj_t& actor, const bool bAllAround) noexcept;
void A_Look(mobj_t& actor) noexcept;
void A_Chase(mobj_t& actor) noexcept;
void A_FaceTarget(mobj_t& actor) noexcept;
void A_PosAttack(mobj_t& actor) noexcept;
void A_SPosAttack(mobj_t& actor) noexcept;
void A_CPosAttack(mobj_t& actor) noexcept;
void A_CPosRefire(mobj_t& actor) noexcept;
void A_SpidAttack(mobj_t& actor) noexcept;
void A_SpidRefire(mobj_t& actor) noexcept;
void A_BspiAttack(mobj_t& actor) noexcept;
void A_TroopAttack(mobj_t& actor) noexcept;
void A_SargAttack(mobj_t& actor) noexcept;
void A_HeadAttack(mobj_t& actor) noexcept;
void A_CyberAttack(mobj_t& actor) noexcept;
void A_BruisAttack(mobj_t& actor) noexcept;
void A_SkelMissile(mobj_t& actor) noexcept;
void A_Tracer(mobj_t& actor) noexcept;
void A_SkelWhoosh() noexcept;
void A_SkelFist() noexcept;
void A_FatRaise() noexcept;
void A_FatAttack1() noexcept;
void A_FatAttack2() noexcept;
void A_FatAttack3() noexcept;
void A_SkullAttack() noexcept;
void A_PainShootSkull() noexcept;
void A_PainAttack() noexcept;
void A_PainDie() noexcept;
void A_Scream() noexcept;
void A_XScream() noexcept;
void A_Pain() noexcept;
void A_Fall() noexcept;
void A_Explode() noexcept;
void A_BossDeath() noexcept;
void A_Hoof() noexcept;
void A_Metal() noexcept;
void A_BabyMetal() noexcept;
void L_MissileHit() noexcept;
void L_SkullBash() noexcept;
