#pragma once

#include <cstdint>

// Sequence identifiers for all sfx and original music tracks in the game
enum sfxenum_t : int32_t {
    sfx_None,
    sfx_sgcock,
    sfx_punch,
    sfx_itmbk,
    sfx_firsht2,
    sfx_barexp,
    sfx_firxpl,
    sfx_pistol,
    sfx_shotgn,
    sfx_plasma,
    sfx_bfg,
    sfx_sawup,
    sfx_sawidl,
    sfx_sawful,
    sfx_sawhit,
    sfx_rlaunc,
    sfx_rxplod,
    sfx_pstart,
    sfx_pstop,
    sfx_doropn,
    sfx_dorcls,
    sfx_stnmov,
    sfx_swtchn,
    sfx_swtchx,
    sfx_itemup,
    sfx_wpnup,
    sfx_oof,
    sfx_telept,
    sfx_noway,
    sfx_dshtgn,
    sfx_dbopn,
    sfx_dbload,
    sfx_dbcls,
    sfx_plpain,
    sfx_pldeth,
    sfx_slop,
    sfx_posit1,
    sfx_posit2,
    sfx_posit3,
    sfx_podth1,
    sfx_podth2,
    sfx_podth3,
    sfx_posact,
    sfx_popain,
    sfx_dmpain,
    sfx_dmact,
    sfx_claw,
    sfx_bgsit1,
    sfx_bgsit2,
    sfx_bgdth1,
    sfx_bgdth2,
    sfx_bgact,
    sfx_sgtsit,
    sfx_sgtatk,
    sfx_sgtdth,
    sfx_brssit,
    sfx_brsdth,
    sfx_cacsit,
    sfx_cacdth,
    sfx_sklatk,
    sfx_skldth,
    sfx_kntsit,
    sfx_kntdth,
    sfx_pesit,
    sfx_pepain,
    sfx_pedth,
    sfx_bspsit,
    sfx_bspdth,
    sfx_bspact,
    sfx_bspwlk,
    sfx_manatk,
    sfx_mansit,
    sfx_mnpain,
    sfx_mandth,
    sfx_firsht,
    sfx_skesit,
    sfx_skedth,
    sfx_skeact,
    sfx_skeatk,
    sfx_skeswg,
    sfx_skepch,
    sfx_cybsit,
    sfx_cybdth,
    sfx_hoof,
    sfx_metal,
    sfx_spisit,
    sfx_spidth,
    sfx_bdopn,
    sfx_bdcls,
    sfx_getpow,
// PsyDoom: sounds for PC Doom II actors which have been added back into the game.
// Also need to preserve sequence numbers for original game music - creating explicit entries for those tracks here.
#if PSYDOOM_MODS
    music_01,
    music_02,
    music_03,
    music_04,
    music_05,
    music_06,
    music_07,
    music_08,
    music_09,
    music_10,
    music_11,
    music_12,
    music_13,
    music_14,
    music_15,
    music_16,
    music_17,
    music_18,
    music_19,
    music_20,
    music_21,
    music_22,
    music_23,
    music_24,
    music_25,
    music_26,
    music_27,
    music_28,
    music_29,
    music_30,
    // PsyDoom: reimplemented Arch-vile
    sfx_vilsit,
    sfx_vipain,
    sfx_vildth,
    sfx_vilact,
    sfx_vilatk,
    sfx_flamst,
    sfx_flame,
    // PsyDoom: reimplemented Wolf SS
    sfx_sssit,
    sfx_ssdth,
    // PsyDoom: reimplemented Commander Keen
    sfx_keenpn,
    sfx_keendt,
    // PsyDoom: reimplemented Icon Of Sin
    sfx_bossit,
    sfx_bospit,
    sfx_bospn,
    sfx_bosdth,
    sfx_boscub,

    // PsyDoom: NOTE: new user music tracks could use sequence ids following the above ones...
    // So a new user track 'music_31' could start at sequence index '136' and so on.

    // PsyDoom: 'NUMSFX' is not sufficient to describe the range of sound effects anymore.
    // There are now two separate sequence id ranges for sound effects, describe them here.
    SFX_RANGE1_BEG = sfx_None,
    SFX_RANGE1_END = sfx_getpow + 1,
    SFX_RANGE2_BEG = sfx_vilsit,
    SFX_RANGE2_END = sfx_boscub + 1,
#else
    NUMSFX
#endif
};
