#pragma once

#include <cstdint>

// Identifiers for all sfx in the game
enum sfxenum_t : int32_t {
    sfx_None,
    sfx_sgcock,
    sfx_punch,
    sfx_itmbk,
    sfx_firsht2,
    sfx_barexp,
    sfx_firxpl,
    sfx_pistol,
    sfx_shotgn,
    sfx_plasma,
    sfx_bfg,
    sfx_sawup,
    sfx_sawidl,
    sfx_sawful,
    sfx_sawhit,
    sfx_rlaunc,
    sfx_rxplod,
    sfx_pstart,
    sfx_pstop,
    sfx_doropn,
    sfx_dorcls,
    sfx_stnmov,
    sfx_swtchn,
    sfx_swtchx,
    sfx_itemup,
    sfx_wpnup,
    sfx_oof,
    sfx_telept,
    sfx_noway,
    sfx_dshtgn,
    sfx_dbopn,
    sfx_dbload,
    sfx_dbcls,
    sfx_plpain,
    sfx_pldeth,
    sfx_slop,
    sfx_posit1,
    sfx_posit2,
    sfx_posit3,
    sfx_podth1,
    sfx_podth2,
    sfx_podth3,
    sfx_posact,
    sfx_popain,
    sfx_dmpain,
    sfx_dmact,
    sfx_claw,
    sfx_bgsit1,
    sfx_bgsit2,
    sfx_bgdth1,
    sfx_bgdth2,
    sfx_bgact,
    sfx_sgtsit,
    sfx_sgtatk,
    sfx_sgtdth,
    sfx_brssit,
    sfx_brsdth,
    sfx_cacsit,
    sfx_cacdth,
    sfx_sklatk,
    sfx_skldth,
    sfx_kntsit,
    sfx_kntdth,
    sfx_pesit,
    sfx_pepain,
    sfx_pedth,
    sfx_bspsit,
    sfx_bspdth,
    sfx_bspact,
    sfx_bspwlk,
    sfx_manatk,
    sfx_mansit,
    sfx_mnpain,
    sfx_mandth,
    sfx_firsht,
    sfx_skesit,
    sfx_skedth,
    sfx_skeact,
    sfx_skeatk,
    sfx_skeswg,
    sfx_skepch,
    sfx_cybsit,
    sfx_cybdth,
    sfx_hoof,
    sfx_metal,
    sfx_spisit,
    sfx_spidth,
    sfx_bdopn,
    sfx_bdcls,
    sfx_getpow,
// PsyDoom: sounds for PC Doom II actors which have been added back into the game
#if PSYDOOM_MODS
    // TODO: replace these placeholder Arch-vile sounds with real ones
    sfx_vilsit = sfx_skesit,
    sfx_vipain = sfx_popain,
    sfx_vildth = sfx_skedth,
    sfx_vilact = sfx_skeact,
    sfx_vilatk = sfx_skeatk,
    sfx_flamst = sfx_manatk,
    sfx_flame  = sfx_manatk,
    // TODO: replace these Wolfenstein SS sounds with real ones
    sfx_sssit  = sfx_posit1,
    sfx_ssdth  = sfx_podth1,
    // TODO: replace these Commander Keen sounds with real ones
    sfx_keenpn = sfx_popain,
    sfx_keendt = sfx_podth1,
    // TODO: replace these Icon Of Sin sounds with real ones
    sfx_bossit = sfx_posit1,
    sfx_bospit = sfx_plasma,
    sfx_bospn  = sfx_popain,
    sfx_bosdth = sfx_podth1,
    sfx_boscub = sfx_pstop,
    // TODO: update this once the sfx list is finalized
    NUMSFX = 90
#else
    NUMSFX
#endif
};
