void P_SlideMove() noexcept;
void P_CompletableFrac() noexcept;
void SL_PointOnSide() noexcept;
void SL_CrossFrac() noexcept;
void CheckLineEnds() noexcept;
void ClipToLine() noexcept;
void SL_CheckLine() noexcept;
void SL_PointOnSide2() noexcept;
void SL_CheckSpecialLines() noexcept;
